// FAIL
// Using it outside of loop

fn main() -> int {

    out it;

}